id: OVERWORLD
version: 0.1.0
author: "Astrash, Sancires"

generator: NOISE_3D

addons:
  - biome-provider-pipeline
  - chunk-generator-noise-3d
  - config-biome
  - config-flora
  - config-noise-function
  - config-ore
  - config-palette
  - config-distributors
  - config-locators
  - config-feature
  - structure-terrascript-loader
  - language-yaml
  - generation-stage-feature

stages:
  - FEATURE

noise:
  simplex:
    dimensions: 2
    type: FBM
    octaves: 4
    function:
      type: OPEN_SIMPLEX_2
      frequency: 0.0075

biomes:
  type: PIPELINE # SINGLE type not working so just using bare pipeline
  resolution: 1
  blend:
    amplitude: 0
    noise:
      type: CONSTANT
  pipeline:
    source:
      type: NOISE
      noise:
        dimensions: 2
        type: CONSTANT
      biomes: FOREST
    stages: []