id: OVERWORLD
version: 0.1.0
author: "Astrash, Sancires"

generator: NOISE_3D

addons:
  biome-provider-pipeline: "0.1.+"
  biome-provider-single: "0.1.+"
  chunk-generator-noise-3d: "0.1.+"
  config-biome: "0.1.+"
  config-flora: "0.1.+"
  config-noise-function: "0.1.+"
  config-ore: "0.1.+"
  config-palette: "0.1.+"
  config-distributors: "0.1.+"
  config-locators: "0.1.+"
  config-feature: "0.1.+"
  structure-terrascript-loader: "0.1.+"
  structure-sponge-loader: "0.1.+"
  language-yaml: "0.1.+"
  generation-stage-feature: "0.1.+"
  structure-function-check-noise-3d: "0.1.+"
  palette-block-shortcut: "0.1.+"
  structure-block-shortcut: "0.1.+"

# ---
# Biome distribution
# ---
# Several preset biome providers are available to choose from below.
# Choosing which one is in use is as simple as commenting the enabled one
# (by adding a # at the start) and uncommenting the one you wish to use.
# You can further configure the behaviour of each one in their respective files.

# Default biome distribution
biomes: $biome-providers/presets/single.yml:biomes

# Single biome - to change the single biome to use, check the configuration file.
#biomes: $biome-providers/presets/single.yml:biomes

# TODO: Continental - Generates large continents
#biomes: $biome-providers/presets/continental.yml:biomes

# TODO: Water world - Ocean biomes only
#biomes: $biome-providers/presets/water_world.yml:biomes

# TODO: Desert world - Hot biomes only
#biomes: $biome-providers/presets/desert_world.yml:biomes

# TODO: Frozen World - Frozen biomes only
#biomes: $biome-providers/presets/frozen_world.yml:biomes

# Terrain test pipeline
#biomes: $biomes/abstract/terrain/test/pipeline.yml:biomes

stages:
  - type: FEATURE
    id: preprocessors
  - type: FEATURE
    id: lava
  - type: FEATURE
    id: slabs
  - type: FEATURE
    id: ores
  - type: FEATURE
    id: deposits
  - type: FEATURE
    id: flora
  - type: FEATURE
    id: trees

functions:
  "<<":
    - math/functions/terrace.yml:functions
    - math/functions/lerp.yml:functions
    - math/functions/maskSmooth.yml:functions

samplers:
  "<<":
    - math/samplers/simplex.yml:samplers
