stages:
  - type: REPLACE_LIST
    sampler:
      type: EXPRESSION
      expression: precipitation(x, z)

    default-from: tropical-rainforest
    default-to:
      - hot-desert: 5
      - hot-steppe: 2
      - tropical-savanna-dry: 1
      - tropical-monsoon: 2
      - tropical-rainforest: 3
    to:
      tropical-monsoon:
        - hot-desert: 5
        - hot-steppe: 2
        - tropical-savanna-dry: 1
        - tropical-monsoon: 2
        - tropical-monsoon: 3
      tropical-savanna-wet:
        - hot-steppe: 5
        - hot-steppe: 2
        - tropical-savanna-wet: 1
        - tropical-savanna-wet: 2
        - tropical-savanna-wet: 3
      hot-coast:
        - arid-coast: 6
        - temperate-coast: 1
        - tropical-coast: 1
        - tropical-coast: 2
        - tropical-coast: 3
  
      temperate-hot-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - temperate-mediterranean-hot-summer: 1
        - temperate-hot-summer: 5
      temperate-warm-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - temperate-mediterranean-warm-summer: 1
        - temperate-warm-summer: 5
      temperate-cold-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - temperate-mediterranean-warm-summer: 1
        - temperate-cold-summer: 5
  
      boreal-hot-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - boreal-dry-winter-hot-summer: 1
        - boreal-warm-summer: 1
        - boreal-warm-summer: 2
        - boreal-hot-summer: 2
      boreal-warm-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - boreal-dry-winter-warm-summer: 2
        - boreal-warm-summer: 2
        - boreal-warm-summer: 2
      boreal-cold-summer:
        - boreal-dry-winter-cold-summer: 1
        - boreal-cold-summer: 1
        - boreal-cold-summer: 1
      boreal-very-cold-winter:
        - boreal-dry-winter-very-cold-summer: 1
        - boreal-very-cold-winter: 1
        - boreal-very-cold-winter: 1
