id: ENVIRONMENT_LAND_POLAR_ICE_CAP
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3938c9
    water-fog: 0x50533
    sky: 0x7fa1ff

  climate:
    precipitation: snow
    temperature: 0.0
    temperature-modifier: frozen
    downfall: 0.5