id: ENVIRONMENT_LAND_POLAR_TUNDRA
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3d57d6
    water-fog: 0x50533
    sky: 0x839eff

  climate:
    precipitation: snow
    temperature: -0.5
    downfall: 0.4