biomes:
  type: PIPELINE
  resolution: 2
  initial-size: 50
  blend:
    amplitude: 1
    noise:
      type: GAUSSIAN
  pipeline:
    source: $biome-providers/sources/basic_continents.yml:source
    stages:
      - << biome-providers/stages/distribute_elevation_zones.yml:stages
      - << biome-providers/stages/distribute_temperature_zones.yml:stages
      - << biome-providers/stages/distribute_humidity_zones.yml:stages

      - << biome-providers/stages/add_desert_variants.yml:stages

      #- << biome-providers/stages/expand.yml:stages

      - << biome-providers/stages/add_rivers.yml:stages

      - type: REPLACE
        from: tbd
        to:
          - MYSTERY_ZONE: 1
        noise:
          dimensions: 2
          type: CONSTANT
