samplers:
  climate-variation:
    dimensions: 2
    type: LINEAR
    min: -0.8
    max: 0.8
    function:
      type: CELLULAR
      return: CellValue
      frequency: 0.1

biomes:
  type: PIPELINE
  resolution: 2
  initial-size: 50
  blend:
    amplitude: 1
    noise:
      type: GAUSSIAN
  pipeline:
    source: $biome-providers/sources/basic_continents.yml:source
    stages:
      # Climate distribution
      - << biome-providers/stages/land/distribute_land_climates.yml:stages

      # Land climate variations
      - << biome-providers/stages/land/climates/arid_land_variations.yml:stages
      - << biome-providers/stages/land/climates/tropical_land_variations.yml:stages
      - << biome-providers/stages/land/climates/subtropical_land_variations.yml:stages
      - << biome-providers/stages/land/climates/temperate_land_variations.yml:stages
      - << biome-providers/stages/land/climates/temperate_land_variations.yml:stages
      - << biome-providers/stages/land/climates/montane_land_variations.yml:stages
      - << biome-providers/stages/land/climates/boreal_land_variations.yml:stages
      - << biome-providers/stages/land/climates/arctic_land_variations.yml:stages

      # Expand
      - << biome-providers/stages/expand.yml:stages
      
      # Rivers
      - << biome-providers/stages/add_rivers.yml:stages
