stages:
  - type: REPLACE
    from: $biome-providers/aliases.yml:subtropical-tag
    to:
      - EVERGREEN_FOREST: 1
      - OVERGROWN_CLIFFS: 1
    noise: $biome-providers/default.yml:samplers.climate-variation