id: BASE
type: BIOME
abstract: true
extends:
  - DEPOSITS_DEFAULT
  - ORES_DEFAULT

slant-depth: 15

ocean:
  palette: BLOCK:minecraft:water
  level: $meta.yml:ocean-level

features:
  global-preprocessors:
    - LAVA_FLOOR
    - UNDERGROUND_LAVA_COLUMNS
    - WOOD_WATER_DAM
    - CAVE_GLOW_LICHEN
    - TEXTURED_STONE_SLANT
  preprocessors:
    - CONTAIN_FLOATING_WATER
  underwater-flora:
    - KELP
    - SEAGRASS