id: ENVIRONMENT_LAND_MARITIME_FROZEN
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3d57d6
    water-fog: 0x50533
    sky: 0x7fa1ff

  climate:
    precipitation: snow
    temperature: 0.05
    downfall: 0.3