id: ENVIRONMENT_LAND_MARITIME_WET
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3f76e4
    water-fog: 0x50533
    sky: 0x78a7ff

  climate:
    precipitation: rain
    temperature: 0.8
    downfall: 0.4