stages:
  - type: REPLACE_LIST
    sampler:
      type: EXPRESSION
      expression: precipitation(x, z)

    default-from: tropical-rainforest
    default-to:
      - hot-desert: 5
      - hot-steppe: 1
      - tropical-savanna-dry: 1
      - tropical-monsoon: 2
      - tropical-rainforest: 3
    to:
      tropical-monsoon:
        - hot-desert: 5
        - hot-steppe: 1
        - tropical-savanna-dry: 1
        - tropical-monsoon: 2
        - tropical-monsoon: 3
      tropical-savanna-wet:
        - hot-steppe: 5
        - hot-steppe: 1
        - tropical-savanna-wet: 1
        - tropical-savanna-wet: 2
        - tropical-savanna-wet: 3
      hot-coast:
        - arid-coast: 5
        - temperate-coast: 1
        - tropical-coast: 1
        - tropical-coast: 2
        - tropical-coast: 3
      hot-plateau:
        - desert-plateau: 5
        - temperate-plateau: 1
        - tropical-plateau: 1
        - tropical-plateau: 2
        - tropical-plateau: 3
      hot-crater-lake:
        - desert-crater-lake: 5
        - temperate-crater-lake: 1
        - tropical-crater-lake: 1
        - tropical-crater-lake: 2
        - tropical-crater-lake: 3
      hot-extinct-volcano:
        - desert-extinct-volcano: 5
        - temperate-extinct-volcano: 1
        - tropical-extinct-volcano: 1
        - tropical-extinct-volcano: 2
        - tropical-extinct-volcano: 3
  
      temperate-hot-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - temperate-mediterranean-hot-summer: 1
        - temperate-hot-summer: 5
      temperate-warm-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - temperate-mediterranean-warm-summer: 1
        - temperate-warm-summer: 5
      temperate-cold-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - temperate-mediterranean-warm-summer: 1
        - temperate-cold-summer: 5

      temperate-plateau:
        - cold-desert-plateau: 4
        - cold-desert-plateau: 1
        - temperate-plateau: 1
        - temperate-plateau: 5
      temperate-crater-lake:
        - cold-desert-crater-lake: 4
        - cold-desert-crater-lake: 1
        - temperate-crater-lake: 1
        - temperate-crater-lake: 5
      temperate-extinct-volcano:
        - cold-desert-extinct-volcano: 4
        - cold-desert-extinct-volcano: 1
        - temperate-extinct-volcano: 1
        - temperate-extinct-volcano: 5
  
      boreal-hot-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - boreal-dry-winter-hot-summer: 1
        - boreal-warm-summer: 1
        - boreal-warm-summer: 2
        - boreal-hot-summer: 2
      boreal-warm-summer:
        - cold-desert: 4
        - cold-steppe: 1
        - boreal-dry-winter-warm-summer: 2
        - boreal-warm-summer: 2
        - boreal-warm-summer: 2
      boreal-cold-summer:
        - boreal-dry-winter-cold-summer: 1
        - boreal-cold-summer: 1
        - boreal-cold-summer: 1
      boreal-very-cold-winter:
        - boreal-dry-winter-very-cold-summer: 1
        - boreal-very-cold-winter: 1
        - boreal-very-cold-winter: 1
