id: ENVIRONMENT_LAND_DRY_WARM_SEMI_ARID
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3f76e4
    water-fog: 0x50533
    sky: 0x6eb1ff

  climate:
    temperature: 1.5
    downfall: 0.2