id: ENVIRONMENT_LAND_DRY_COLD_SEMI_ARID
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x2080C9
    water-fog: 0x2080C9
    sky: 0x839eff
    grass: 0x96b480
    foliage: 0x86b480

  climate:
    temperature: 0.25
    downfall: 0.5