id: ENVIRONMENT_MARINE_OCEAN
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3f76e4
    water-fog: 0x50533
    sky: 0x7ba4ff

  climate:
    precipitation: rain
    temperature: 0.5
    downfall: 0.5