id: ENVIRONMENT_MARINE_OCEAN_FROZEN
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0xc0d8ff
    water: 0x3938c9
    water-fog: 0x50533
    sky: 0x7fa1ff

  climate:
    precipitation: rain
    temperature: 0.5
    temperature-modifier: frozen
    downfall: 0.5
