name: Zip Files

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: ./
          dest: result.zip
      - name: Archive result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: origen-build-${{ github.sha }}.zip
          path: result.zip
