biomes:
  type: PIPELINE
  resolution: 2
  initial-size: 50
  blend:
    amplitude: 1
    noise:
      type: GAUSSIAN
  pipeline:
    source:
      type: NOISE
      noise:
        dimensions: 2
        type: LINEAR
        min: -0.8
        max: 0.8
        function:
          type: CELLULAR
          return: CellValue
          frequency: 0.03
      biomes:
        - PLAINS: 1
        - PRAIRIE: 1
        - STEPPE: 1
        - BIRCH_FOREST: 1
        - FOREST: 1
        - ARID_SPIKES: 1
        - DESERT: 1
        - DESERT_SPIKES: 1
        - DESERT_SPIKES_GOLD: 1
    stages:
      - << biome-providers/stages/add_rivers.yml:stages
